

services:
  db:
    image: mysql:8.0
    container_name: clinic-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: clinic_db
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./database/migrations:/docker-entrypoint-initdb.d

  backend:
    build: ./backend
    container_name: clinic-backend
    command: npm run dev
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: clinic_db
    depends_on:
      - db


volumes:
  mysql_data:
